[package]
name = "lecture_rs_book"
version = "0.1.0"
edition = "2021"
authors = ["lsh <sample@example.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand ="0.3.14"